#!/usr/bin/env bash

# HoursBoard
# Copyright 2013 Nitesh Morajkar
# See LICENSE for details.

# Check if file exists
dirName="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
basePath=$(cat $dirName/conf | head -n 1)

# Make log dir if it doesn't exists
if [ ! -d $basePath ]; then
	mkdir -m 755 $basePath
fi

# Check if log file exists
if [ ! -f $basePath$(date +%F).log ]; then
    touch $basePath$(date +%F).log
    echo "1,$(date +%s)" >> $basePath$(date +%F).log
fi

# Monitor dbus to detect screen lock/unlock event
dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver',member='ActiveChanged'" | while read line ; do 
    if [ x"$(echo "$line" | grep 'boolean true')" != x ] ; then # When log-out
	echo "0,$(date +%s)" >> $basePath$(date +%F).log
    fi
    if [ x"$(echo "$line" | grep 'boolean false')" != x ] ; then # When logs-in
    	counter=0
    	while [ $counter -eq 0 ]
    	do
            textResponse=`zenity --entry --text="Add a logout tag"`
            if [ -n "$textResponse" ]; then
            	echo "1,$(date +%s),$textResponse" >> $basePath$(date +%F).log
            	counter=1
            	break
            fi
    	done
    fi
done
