#!/usr/bin/env bash

# HoursBoard
# Copyright 2013 Nitesh Morajkar
# See LICENSE for details.

# Check if file exists
dirName="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
basePath=$(cat $dirName/conf | head -n 1 | sed 's/\/\+/\//g')

# Make log dir if it doesn't exists
if [ ! -d $basePath ]; then
	mkdir -m 755 $basePath
fi

# Check if log file exists
if [ ! -f $basePath$(date +%F).log ]; then
    touch $basePath$(date +%F).log
    echo "1,$(date +%s),LoggedIn" >> $basePath$(date +%F).log
else
    lastCount=`tail -n 1 $basePath$(date +%F).log | awk -F "," '{print $1}'`
    if [ $lastCount == 0 ]; then
        echo "1,$(date +%s),LoggedInAgain" >> $basePath$(date +%F).log
    fi
fi

# Monitor dbus to detect screen lock/unlock event
dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver',member='ActiveChanged'" | while read line ; do 
    if [ x"$(echo "$line" | grep 'boolean true')" != x ] ; then # When log-out
	   echo "0,$(date +%s)" >> $basePath$(date +%F).log
    fi
    if [ x"$(echo "$line" | grep 'boolean false')" != x ] ; then # When logs-in
        curDate=`date +%F`
        curUnixTime=`date +%s`
    	
        textResponse=`zenity --entry --text="Add a logout tag $curDate $(date +%R)"`

        # If textResponse contains space, then log it as flag 2
        if [ "$textResponse" == " " ]; then
        	echo "2,$curUnixTime,dc" >> $basePath$curDate.log	
        elif [ -n "$textResponse" ]; then
        	echo "1,$curUnixTime,$textResponse" >> $basePath$curDate.log
	fi
    fi
done
